pipeline:
  name: git-clone-bv
  identifier: gitclonebv
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        repoName: test-bv
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: bvgit
                    repoName: terraform-compute-engine
                    build:
                      type: branch
                      spec:
                        branch: Main
